package kotlinexample.coroutineexample.exception

// 예외를 처리하는 두 번째 방법 async() 빌더에서 사용하는 방법,

fun main(args: Array<String>) {

}